# name: Enable auto-merge for Dependabot PRs

# on:
#   pull_request_target:
#     types:
#       - opened
#       - reopened
#       - synchronize
#       - labeled
#       - ready_for_review

# permissions:
#   contents: write
#   pull-requests: write

# jobs:
#   enable-auto-merge:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Enable auto-merge for dependabot PRs with label
#         if: |
#           github.event.pull_request.user.login == 'dependabot[bot]' &&
#           contains(github.event.pull_request.labels.*.name, 'dependencies')
#         uses: peter-evans/enable-pull-request-automerge@v3
#         with:
#           merge-method: squash
#           pull-request-number: ${{ github.event.pull_request.number }}
