name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const mergeable = pr.data.mergeable;
            const mergeable_state = pr.data.mergeable_state;

            console.log("Mergeable:", mergeable);
            console.log("Mergeable State:", mergeable_state);

            if (mergeable && mergeable_state === "clean") {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data.number,
                merge_method: "squash"
              });
              console.log("✅ PR merged.");
            } else {
              console.log("⛔️ Not safe to merge (conflict or checks not passing).");
            }
