name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - ready_for_review

permissions:
  pull-requests: write
  contents: write
  statuses: read
  checks: read

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          retries: 3
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const { mergeable, mergeable_state, number: prNumber, head } = pr.data;

            console.log("Mergeable:", mergeable);
            console.log("Mergeable State:", mergeable_state);

            // Get combined status for the HEAD commit
            const status = await github.rest.repos.getCombinedStatusForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: head.sha
            });

            const allChecksPass = status.data.state === "success";
            console.log("Status checks state:", status.data.state);

            if (mergeable && mergeable_state === "clean" && allChecksPass) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: "squash"
              });
              console.log("✅ PR auto-merged.");
            } else {
              console.log("⛔️ Not safe to merge yet. Either conflicts, CI not done, or failed.");
            }
